using Microsoft.EntityFrameworkCore;
using MedErp.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace MedErp.Infrastructure.EntitiesConfig
{
    public class CountryConfig : IEntityTypeConfiguration<Country>
    {
        public void Configure(EntityTypeBuilder<Country> builder)
        {
            builder.ToTable("Countries");
            builder.HasKey(o => o.Id);

            builder.HasData(BuildSeedData());

        }

        private List<Country> BuildSeedData()
        {
            return new List<Country>()  {
              new Country(){ Id=1,CountryName= "Afghanistan" },
              new Country(){ Id=2,CountryName= "Albania" },
              new Country(){ Id=3,CountryName= "Algeria" },
              new Country(){ Id=4,CountryName= "American Samoa" },
              new Country(){ Id=5,CountryName= "Andorra" },
              new Country(){ Id=6,CountryName= "Angola" },
              new Country(){ Id=7,CountryName= "Anguilla" },
              new Country(){ Id=8,CountryName= "Antarctica" },
              new Country(){ Id=9,CountryName= "Antigua and Barbuda" },
              new Country(){ Id=10,CountryName= "Argentina" },
              new Country(){ Id=11,CountryName= "Armenia" },
              new Country(){ Id=12,CountryName= "Aruba" },
              new Country(){ Id=13,CountryName= "Australia" },
              new Country(){ Id=14,CountryName= "Austria" },
              new Country(){ Id=15,CountryName= "Azerbaijan" },
              new Country(){ Id=16,CountryName= "Bahamas" },
              new Country(){ Id=17,CountryName= "Bahrain" },
              new Country(){ Id=18,CountryName= "Bangladesh" },
              new Country(){ Id=19,CountryName= "Barbados" },
              new Country(){ Id=20,CountryName= "Belarus" },
              new Country(){ Id=21,CountryName= "Belgium" },
              new Country(){ Id=22,CountryName= "Belize" },
              new Country(){ Id=23,CountryName= "Benin" },
              new Country(){ Id=24,CountryName= "Bermuda" },
              new Country(){ Id=25,CountryName= "Bhutan" },
              new Country(){ Id=26,CountryName= "Bolivia" },
              new Country(){ Id=27,CountryName= "Bosnia and Herzegovina" },
              new Country(){ Id=28,CountryName= "Botswana" },
              new Country(){ Id=29,CountryName= "Bouvet Island" },
              new Country(){ Id=30,CountryName= "Brazil" },
              new Country(){ Id=31,CountryName= "British Indian Ocean Territories" },
              new Country(){ Id=32,CountryName= "Brunei Darussalam" },
              new Country(){ Id=33,CountryName= "Bulgaria" },
              new Country(){ Id=34,CountryName= "Burkina Faso" },
              new Country(){ Id=35,CountryName= "Burundi" },
              new Country(){ Id=36,CountryName= "Cambodia" },
              new Country(){ Id=37,CountryName= "Cameroon" },
              new Country(){ Id=38,CountryName= "Canada" },
              new Country(){ Id=39,CountryName= "Cape Verde" },
              new Country(){ Id=40,CountryName= "Cayman Islands" },
              new Country(){ Id=41,CountryName= "Central African Republic" },
              new Country(){ Id=42,CountryName= "Chad" },
              new Country(){ Id=43,CountryName= "Chile" },
              new Country(){ Id=44,CountryName= "China" },
              new Country(){ Id=45,CountryName= "Christmas Island" },
              new Country(){ Id=46,CountryName= "Cocos Islands" },
              new Country(){ Id=47,CountryName= "Columbia" },
              new Country(){ Id=48,CountryName= "Comoros" },
              new Country(){ Id=49,CountryName= "Congo" },
              new Country(){ Id=50,CountryName= "Cook Islands" },
              new Country(){ Id=51,CountryName= "Costa Rica" },
              new Country(){ Id=52,CountryName= "Cote D'ivoire" },
              new Country(){ Id=53,CountryName= "Croatia" },
              new Country(){ Id=54,CountryName= "Cuba" },
              new Country(){ Id=55,CountryName= "Cyprus" },
              new Country(){ Id=56,CountryName= "Czech Republic" },
              new Country(){ Id=57,CountryName= "Djibouti" },
              new Country(){ Id=58,CountryName= "Dominica" },
              new Country(){ Id=59,CountryName= "Dominican Republic" },
              new Country(){ Id=60,CountryName= "East Timor" },
              new Country(){ Id=61,CountryName= "Ecuador" },
              new Country(){ Id=62,CountryName= "Egypt" },
              new Country(){ Id=63,CountryName= "El Salvador" },
              new Country(){ Id=64,CountryName= "Equatorial Guinea" },
              new Country(){ Id=65,CountryName= "Eritrea" },
              new Country(){ Id=66,CountryName= "Estonia" },
              new Country(){ Id=67,CountryName= "Ethiopia" },
              new Country(){ Id=68,CountryName= "Falkland Islands" },
              new Country(){ Id=69,CountryName= "Faroe Islands" },
              new Country(){ Id=70,CountryName= "Fiji" },
              new Country(){ Id=71,CountryName= "Finland" },
              new Country(){ Id=72,CountryName= "France" },
              new Country(){ Id=73,CountryName= "France, Metropolitan" },
              new Country(){ Id=74,CountryName= "French Guiana" },
              new Country(){ Id=75,CountryName= "French Polynesia" },
              new Country(){ Id=76,CountryName= "French Southern Territories" },
              new Country(){ Id=77,CountryName= "FYROM" },
              new Country(){ Id=78,CountryName= "Gabon" },
              new Country(){ Id=79,CountryName= "Gambia" },
              new Country(){ Id=80,CountryName= "Georgia" },
              new Country(){ Id=81,CountryName= "Germany" },
              new Country(){ Id=82,CountryName= "Ghana" },
              new Country(){ Id=83,CountryName= "Gibraltar" },
              new Country(){ Id=84,CountryName= "Greece" },
              new Country(){ Id=85,CountryName= "Greenland" },
              new Country(){ Id=86,CountryName= "Grenada" },
              new Country(){ Id=87,CountryName= "Guadeloupe" },
              new Country(){ Id=88,CountryName= "Guam" },
              new Country(){ Id=89,CountryName= "Guatemala" },
              new Country(){ Id=90,CountryName= "Guinea" },
              new Country(){ Id=91,CountryName= "Guinea-Bissau" },
              new Country(){ Id=92,CountryName= "Guyana" },
              new Country(){ Id=93,CountryName= "Haiti" },
              new Country(){ Id=94,CountryName= "Heard Island And Mcdonald Islands" },
              new Country(){ Id=95,CountryName= "Honduras" },
              new Country(){ Id=96,CountryName= "Hong Kong" },
              new Country(){ Id=97,CountryName= "Hungary" },
              new Country(){ Id=98,CountryName= "Iceland" },
              new Country(){ Id=99,CountryName= "India" },
              new Country(){ Id=100,CountryName= "Indonesia" },
              new Country(){ Id=101,CountryName= "Iran" },
              new Country(){ Id=102,CountryName= "Iraq" },
              new Country(){ Id=103,CountryName= "Ireland" },
              //new Country(){ Id=104,CountryName= "Israel" },
              new Country(){ Id=105,CountryName= "Italy" },
              new Country(){ Id=106,CountryName= "Jamaica" },
              new Country(){ Id=107,CountryName= "Japan" },
              new Country(){ Id=108,CountryName= "Jordan" },
              new Country(){ Id=109,CountryName= "Kazakhstan" },
              new Country(){ Id=110,CountryName= "Kenya" },
              new Country(){ Id=111,CountryName= "Kiribati" },
              new Country(){ Id=112,CountryName= "Korea, Democratic Peoples Republic of" },
              new Country(){ Id=113,CountryName= "Korea, Republic of" },
              new Country(){ Id=114,CountryName= "Kuwait" },
              new Country(){ Id=115,CountryName= "Kyrgyzstan" },
              new Country(){ Id=116,CountryName= "Lao Peoples Democratic Republic" },
              new Country(){ Id=117,CountryName= "Latvia" },
              new Country(){ Id=118,CountryName= "Lebanon" },
              new Country(){ Id=119,CountryName= "Lesotho" },
              new Country(){ Id=120,CountryName= "Liberia" },
              new Country(){ Id=121,CountryName= "Libyan Arab Jamahiriya" },
              new Country(){ Id=122,CountryName= "Liechtenstein" },
              new Country(){ Id=123,CountryName= "Lithuania" },
              new Country(){ Id=124,CountryName= "Luxembourg" },
              new Country(){ Id=125,CountryName= "Macau" },
              new Country(){ Id=126,CountryName= "Madagascar" },
              new Country(){ Id=127,CountryName= "Malawi" },
              new Country(){ Id=128,CountryName= "Malaysia" },
              new Country(){ Id=129,CountryName= "Maldives" },
              new Country(){ Id=130,CountryName= "Mali" },
              new Country(){ Id=131,CountryName= "Malta" },
              new Country(){ Id=132,CountryName= "Marshall Islands" },
              new Country(){ Id=133,CountryName= "Martinique" },
              new Country(){ Id=134,CountryName= "Mauritania" },
              new Country(){ Id=135,CountryName= "Mauritius" },
              new Country(){ Id=136,CountryName= "Mayotte" },
              new Country(){ Id=137,CountryName= "Mexico" },
              new Country(){ Id=138,CountryName= "Micronesia" },
              new Country(){ Id=139,CountryName= "Moldova" },
              new Country(){ Id=140,CountryName= "Mongolia" },
              new Country(){ Id=141,CountryName= "Montserrat" },
              new Country(){ Id=142,CountryName= "Morocco" },
              new Country(){ Id=143,CountryName= "Monaco" },
              new Country(){ Id=144,CountryName= "Myanmar" },
              new Country(){ Id=145,CountryName= "Mozambique" },
              new Country(){ Id=146,CountryName= "Namibia" },
              new Country(){ Id=147,CountryName= "Nauru" },
              new Country(){ Id=148,CountryName= "Nepal" },
              new Country(){ Id=149,CountryName= "Netherlands" },
              new Country(){ Id=150,CountryName= "Netherlands Antilles" },
              new Country(){ Id=151,CountryName= "New Caledonia" },
              new Country(){ Id=152,CountryName= "New Zealand" },
              new Country(){ Id=153,CountryName= "Nicaragua" },
              new Country(){ Id=154,CountryName= "Niger" },
              new Country(){ Id=155,CountryName= "Nigeria" },
              new Country(){ Id=156,CountryName= "Niue" },
              new Country(){ Id=157,CountryName= "Norfolk Island" },
              new Country(){ Id=158,CountryName= "Northern Mariana Islands" },
              new Country(){ Id=159,CountryName= "Norway" },
              new Country(){ Id=160,CountryName= "Oman" },
              new Country(){ Id=161,CountryName= "Pakistan" },
              new Country(){ Id=162,CountryName= "palestine" },
              new Country(){ Id=163,CountryName= "Palau" },
              new Country(){ Id=164,CountryName= "Panama" },
              new Country(){ Id=165,CountryName= "Papua New Guinea" },
              new Country(){ Id=166,CountryName= "Paraguay" },
              new Country(){ Id=167,CountryName= "Peru" },
              new Country(){ Id=168,CountryName= "Philippines" },
              new Country(){ Id=169,CountryName= "Pitcairn" },
              new Country(){ Id=170,CountryName= "Poland" },
              new Country(){ Id=171,CountryName= "Portugal" },
              new Country(){ Id=172,CountryName= "Puerto Rico" },
              new Country(){ Id=173,CountryName= "Qatar" },
              new Country(){ Id=174,CountryName= "Reunion" },
              new Country(){ Id=175,CountryName= "Romania" },
              new Country(){ Id=176,CountryName= "Russian Federation" },
              new Country(){ Id=177,CountryName= "Rwanda" },
              new Country(){ Id=178,CountryName= "Saint Helena" },
              new Country(){ Id=179,CountryName= "Saint Kitts and Nevis" },
              new Country(){ Id=180,CountryName= "Saint Lucia" },
              new Country(){ Id=181,CountryName= "Saint Pierre and Miquelon" },
              new Country(){ Id=182,CountryName= "Saint Vincent and The Grenadines" },
              new Country(){ Id=183,CountryName= "Samoa" },
              new Country(){ Id=184,CountryName= "San Marino" },
              new Country(){ Id=185,CountryName= "Sao Tome and Principe" },
              new Country(){ Id=186,CountryName= "Saudi Arabia" },
              new Country(){ Id=187,CountryName= "Senegal" },
              new Country(){ Id=188,CountryName= "Seychelles" },
              new Country(){ Id=189,CountryName= "Sierra Leone" },
              new Country(){ Id=190,CountryName= "Singapore" },
              new Country(){ Id=191,CountryName= "Slovakia" },
              new Country(){ Id=192,CountryName= "Slovenia" },
              new Country(){ Id=193,CountryName= "Solomon Islands" },
              new Country(){ Id=194,CountryName= "Somalia" },
              new Country(){ Id=195,CountryName= "South Africa" },
              new Country(){ Id=196,CountryName= "South Georgia and Sandwich Islands" },
              new Country(){ Id=197,CountryName= "Spain" },
              new Country(){ Id=198,CountryName= "Sri Lanka" },
              new Country(){ Id=199,CountryName= "Sudan" },
              new Country(){ Id=200,CountryName= "Suriname" },
              new Country(){ Id=201,CountryName= "Svalbard and JanMayen" },
              new Country(){ Id=202,CountryName= "Swaziland" },
              new Country(){ Id=203,CountryName= "Sweden" },
              new Country(){ Id=204,CountryName= "Switzerland" },
              new Country(){ Id=205,CountryName= "Syrian Arab Republic" },
              new Country(){ Id=206,CountryName= "Taiwan" },
              new Country(){ Id=207,CountryName= "Tajikistan" },
              new Country(){ Id=208,CountryName= "Tanzania" },
              new Country(){ Id=209,CountryName= "Thailand" },
              new Country(){ Id=210,CountryName= "Tokelau" },
              new Country(){ Id=211,CountryName= "Tonga" },
              new Country(){ Id=212,CountryName= "Trinidad and Tobago" },
              new Country(){ Id=213,CountryName= "Tunisia" },
              new Country(){ Id=214,CountryName= "Togo" },
              new Country(){ Id=215,CountryName= "Turkey" },
              new Country(){ Id=216,CountryName= "Turkmenistan" },
              new Country(){ Id=217,CountryName= "Turks and Caicos Islands" },
              new Country(){ Id=218,CountryName= "Tuvalu" },
              new Country(){ Id=219,CountryName= "Uganda" },
              new Country(){ Id=220,CountryName= "Ukraine" },
              new Country(){ Id=221,CountryName= "United Arab Emirates" },
              new Country(){ Id=222,CountryName= "United Kingdom" },
              new Country(){ Id=223,CountryName= "United States" },
              new Country(){ Id=224,CountryName= "Uruguay" },
              new Country(){ Id=225,CountryName= "Uzbekistan" },
              new Country(){ Id=226,CountryName= "Vanuatu" },
              new Country(){ Id=227,CountryName= "Vatican City State" },
              new Country(){ Id=228,CountryName= "Venezuela" },
              new Country(){ Id=229,CountryName= "Vietnam" },
              new Country(){ Id=230,CountryName= "Virgin Islands (British)" },
              new Country(){ Id=231,CountryName= "Virgin Islands (U.S.)" },
              new Country(){ Id=232,CountryName= "Wallis And Futuna Islands" },
              new Country(){ Id=233,CountryName= "Western Sahara" },
              new Country(){ Id=234,CountryName= "Yemen" },
              new Country(){ Id=235,CountryName= "Yugoslavia" },
              new Country(){ Id=236,CountryName= "Zaire" },
              new Country(){ Id=237,CountryName= "Zambia" },
              new Country(){ Id=238,CountryName= "Zimbabwe" },
              new Country(){ Id=239,CountryName= "Guernsey" },
              new Country(){ Id=240,CountryName= "Malaga" },
              new Country(){ Id=241,CountryName= "Denmark" },
              new Country(){ Id=242,CountryName= "Jersey" }
          
 
            };
        }
    }
}
